import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { calculateBalances } from "@/lib/balances";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

async function requireTripAccess(tripId: string, userId: string) {
  return prisma.tripMember.findUnique({
    where: { userId_tripId: { userId, tripId } },
  });
}

export async function GET(
  req: Request,
  { params }: { params: { tripId: string } }
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const member = await requireTripAccess(params.tripId, session.user.id);
  if (!member) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const trip = await prisma.trip.findUnique({
    where: { id: params.tripId },
    include: {
      members: {
        include: { user: { select: { id: true, name: true, email: true } } },
      },
      expenses: {
        include: {
          paidBy: { select: { id: true, name: true } },
          splits: { include: { user: { select: { id: true, name: true } } } },
        },
        orderBy: { date: "desc" },
      },
      settlements: {
        include: {
          payer: { select: { id: true, name: true } },
          receiver: { select: { id: true, name: true } },
        },
      },
    },
  });

  if (!trip) {
    return NextResponse.json({ error: "Trip not found" }, { status: 404 });
  }

  const balances = calculateBalances(
    trip.expenses.map((e) => ({
      amount: e.amount,
      paidById: e.paidById,
      splits: e.splits.map((s) => ({ userId: s.userId, amount: s.amount })),
    })),
    trip.settlements.map((s) => ({
      amount: s.amount,
      payerId: s.payerId,
      receiverId: s.receiverId,
      status: s.status,
    }))
  );

  const url = new URL(req.url);
  const format = url.searchParams.get("format");

  if (format === "pdf") {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("Pesoman - Trip Summary", 14, 20);

    doc.setFontSize(12);
    doc.text(`Trip: ${trip.name}`, 14, 35);
    doc.text(`Currency: ${trip.currency}`, 14, 42);
    doc.text(`Total Expenses: ${trip.currency} ${balances.groupTotal.toFixed(2)}`, 14, 49);

    autoTable(doc, {
      startY: 60,
      head: [["Date", "Title", "Category", "Amount", "Paid By", "Split Among"]],
      body: trip.expenses.map((e) => [
        new Date(e.date).toLocaleDateString(),
        e.title,
        e.category,
        `${trip.currency} ${e.amount.toFixed(2)}`,
        e.paidBy.name,
        e.splits.map((s) => s.user.name).join(", "),
      ]),
    });

    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [["Member", "Total Paid", "Total Owed", "Net Balance"]],
      body: Object.entries(balances.perPersonTotal).map(([userId, data]) => {
        const member = trip.members.find((m) => m.user.id === userId);
        return [
          member?.user.name || "Unknown",
          `${trip.currency} ${data.totalPaid.toFixed(2)}`,
          `${trip.currency} ${data.totalOwed.toFixed(2)}`,
          `${data.net >= 0 ? "+" : ""}${trip.currency} ${data.net.toFixed(2)}`,
        ];
      }),
    });

    doc.setFontSize(10);
    doc.text("Generated by Pesoman - pesoman.app", 14, doc.internal.pageSize.height - 10);

    const pdfBuffer = doc.output("arraybuffer");
    return new NextResponse(pdfBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${trip.name}-summary.pdf"`,
      },
    });
  }

  return NextResponse.json({
    trip,
    balances,
  });
}
